-- Sigma DataTech Silver Layer Fix Queries
-- Generated by CrewAI DQ Crew | 2026-05-29T15:36:22.161085

-- FIX: NULL values in columns | SEVERITY: MEDIUM | RISK: LOW
   UPDATE silver_transactions
   SET 
       merchant_id = COALESCE(merchant_id, 'UNKNOWN'),
       customer_id = COALESCE(customer_id, 'UNKNOWN'),
       payment_method = COALESCE(payment_method, 'UNKNOWN')
   WHERE 
       merchant_id IS NULL OR customer_id IS NULL OR payment_method IS NULL;

-- FIX: Amounts 3x above average | SEVERITY: MEDIUM | RISK: MEDIUM
   WITH average_amount AS (
       SELECT 
           AVG(amount) AS avg_amount
       FROM 
           silver_transactions
   )
   UPDATE silver_transactions st
   SET 
       amount = (SELECT avg_amount FROM average_amount)
   FROM 
       average_amount
   WHERE 
       st.amount > 3 * average_amount.avg_amount;

-- FIX: Negative amounts | SEVERITY: CRITICAL | RISK: HIGH
   UPDATE silver_transactions
   SET 
       amount = 0
   WHERE 
       amount < 0;
   -- ROLLBACK: To undo this, you would need to restore the original data from a backup or use application logs to recalculate the correct amounts.

-- FIX: Duplicate `transaction_id`s | SEVERITY: CRITICAL | RISK: HIGH
   WITH duplicates AS (
       SELECT 
           transaction_id, 
           ROW_NUMBER() OVER (PARTITION BY transaction_id ORDER BY transaction_date DESC) AS rn
       FROM 
           silver_transactions
   )
   DELETE FROM silver_transactions
   USING duplicates
   WHERE 
       silver_transactions.transaction_id = duplicates.transaction_id
       AND duplicates.rn > 1;
   -- ROLLBACK: To undo this, you would need to restore the original data from a backup.

-- FIX: Future-dated transactions | SEVERITY: HIGH | RISK: HIGH
   UPDATE silver_transactions
   SET 
       transaction_date = CURRENT_DATE()
   WHERE 
       STRFTIME(transaction_date, '%Y-%m-%d') > CURRENT_DATE();
   -- ROLLBACK: To undo this, you would need to restore the original data from a backup.