"""
Sigma DataTech Transaction Analytics Pipeline
AI-Generated by Module 1 | Day 7 — Pipeline Brain
Generated: 2026-05-26T09:32:23.071711+00:00

This file was produced by 1_spec_to_pipeline.py from a plain-English spec.
It is a FIRST DRAFT — review before running against production data.

Architecture: Bronze -> Silver -> Gold (medallion pattern)
"""

# ═══════════════════════════════════════════════════════════════
# SECTION 1: BRONZE + SILVER LAYERS
# ═══════════════════════════════════════════════════════════════
from pyspark.sql import SparkSession
from pyspark.sql.functions import col, lit, coalesce, when, count, countDistinct, current_date, isnull
from pyspark.sql.types import StringType, DoubleType, DateType, IntegerType, TimestampType
from datetime import datetime

def ingest_bronze(spark, input_path, output_path, run_date, run_id):
    # Read CSV with all columns as strings
    bronze_df = spark.read.csv(input_path, header=True, inferSchema=True)
    
    # Add metadata columns
    bronze_df = bronze_df.withColumn("_ingestion_ts", lit(datetime.utcnow()).cast(TimestampType())) \
                         .withColumn("_source_file", lit(input_path)) \
                        .withColumn("_batch_id", lit(run_id))
    
    # Write to Bronze layer partitioned by txn_date
    bronze_df.write.mode('overwrite').partitionBy('txn_date').parquet(output_path)

def transform_silver(spark, bronze_path, merchants_path, output_path, run_date):
    # Read Bronze Parquet with partition pruning on run_date
    bronze_df = spark.read.parquet(bronze_path).where(col("txn_date") == run_date)
    
    # Check if the DataFrame is empty
    if bronze_df.rdd.isEmpty():
        raise Exception("E001: Silver transactions table is empty for date {}".format(run_date))
    
    # Cast columns to correct types
    bronze_df = bronze_df.withColumn("amount", col("amount").cast(DoubleType())) \
                         .withColumn("txn_date", col("txn_date").cast(DateType())) \
                         .withColumn("transaction_id", col("transaction_id").cast(StringType())) \
                         .withColumn("status", col("status").cast(StringType())) \
                        .withColumn("customer_id", col("customer_id").cast(StringType()))
    
    # Filter NULL transaction_id and negative amounts
    bronze_df = bronze_df.filter(col("transaction_id").isNotNull() & (col("amount") >= 0))
    
    # Deduplicate on transaction_id keeping latest _ingestion_ts
    bronze_df = bronze_df.sortWithinPartitions("transaction_id", "_ingestion_ts").dropDuplicates(["transaction_id"])
    
    # Read merchants data and cache it
    merchants_df = spark.read.parquet(merchants_path).cache()
    
    # Join with merchants (broadcast hint)
    bronze_df = bronze_df.join(broadcast(merchants_df), bronze_df["merchant_id"] == merchants_df["merchant_id"], "left")
    
    # Add quality_flag column (CLEAN or UNMATCHED)
    bronze_df = bronze_df.withColumn("quality_flag", when(col("merchant_id").isNotNull(), "CLEAN").otherwise("UNMATCHED"))
    
    # Compute quality metrics
    total_rows = bronze_df.count()
    null_counts = {col: bronze_df.filter(isnull(col)).count() for col in ["amount", "txn_date", "transaction_id", "status", "customer_id"]}
    duplicate_count = total_rows - bronze_df.select("transaction_id").distinct().count()
    duplicate_rate = duplicate_count / total_rows
    schema_match = 1 if set(["transaction_id", "customer_id", "amount", "txn_date", "status"]).issubset(bronze_df.columns) else 0
    
    # Calculate overall_quality_score
    null_rate = sum(null_counts.values()) / total_rows
    overall_quality_score = 100 - (null_rate * 40 + duplicate_rate * 40 + (1 - schema_match) * 20)
    
    # Determine pipeline status
    pipeline_status = "SUCCESS" if overall_quality_score >= 60 else "HALTED"
    schema_alert = schema_match == 0 and overall_quality_score >= 60
    
    # Create data quality scorecard DataFrame
    scorecard_df = spark.createDataFrame([(
        run_date, "ALL", null_counts["amount"] / total_rows, duplicate_rate,
        schema_match, overall_quality_score, pipeline_status, schema_alert
    )], ["run_date", "column_name", "null_rate", "duplicate_rate", "schema_match", "overall_quality_score", "pipeline_status", "schema_alert"])
    
    # Write to Silver layer
    bronze_df.write.mode('overwrite').partitionBy('txn_date').parquet(output_path)
    scorecard_df.write.mode('append').parquet(output_path + "/data_quality_scorecard")

def main():
    # Initialize Spark session
    spark = SparkSession.builder.appName("TransactionsDQPipeline").getOrCreate()
    
    # Define paths and run date
    input_path = "s3://datalake/bronze/transactions/"
    bronze_path = "s3://datalake/bronze/transactions/"
    merchants_path = "s3://datalake/silver/merchants/"
    output_path = "s3://datalake/silver/transactions/"
    run_date = datetime.now().date().isoformat()
    run_id = "run_" + run_date.replace("-", "")
    
    # Execute pipeline stages
    ingest_bronze(spark, input_path, output_path, run_date, run_id)
    transform_silver(spark, bronze_path, merchants_path, output_path, run_date)

if __name__ == "__main__":
    main()


# ═══════════════════════════════════════════════════════════════
# SECTION 2: GOLD AGGREGATION LAYER
# ═══════════════════════════════════════════════════════════════
from pyspark.sql import SparkSession
from pyspark.sql.functions import col, count, countDistinct, isnan, when, lit, sum as _sum
from pyspark.sql.types import StructType, StructField, StringType, DoubleType, IntegerType, DateType

def run_gold(spark, silver_path, gold_output_dir, run_date):
    build_merchant_performance(spark, silver_path, f"{gold_output_dir}/merchant_performance", run_date)
    build_customer_ltv(spark, silver_path, f"{gold_output_dir}/customer_ltv")
    build_daily_summary(spark, silver_path, f"{gold_output_dir}/daily_summary", run_date)
    run_metadata = {
        "run_date": run_date,
        "status": "SUCCESS",
        "error_message": ""
    }
    spark.sparkContext.parallelize([run_metadata]).write.json(f"{gold_output_dir}/run_metadata")

def build_merchant_performance(spark, silver_path, output_path, run_date):
    silver_df = (spark.read.format("delta").load(silver_path)
                 .where(col("txn_date") == run_date)
                .cache())
    
    if silver_df.rdd.isEmpty():
        raise Exception("E001: silver.transactions is missing or empty")
    
    merchant_performance_df = (silver_df.groupBy("merchant_id", "merchant_name", "category", "city", "date")
                              .agg(
                                  total_revenue=_sum(when(col("status") == "COMPLETED", col("amount")).otherwise(0)).alias("total_revenue"),
                                  txn_count=count("*"),
                                  failed_txns=count(when(col("status") == "FAILED", 1))
                              )
                             .withColumn("failure_rate_pct", (col("failed_txns") / col("txn_count")) * 100)
                             .drop("failed_txns"))
    
    merchant_performance_df.write.partitionBy("date").mode("overwrite").parquet(output_path)

def build_customer_ltv(spark, silver_path, output_path):
    silver_df = (spark.read.format("delta").load(silver_path)
                .where(col("status") == "COMPLETED")
                .cache())
    
    if silver_df.rdd.isEmpty():
        raise Exception("E002: silver.transactions is missing or empty")
    
    customer_ltv_df = (silver_df.groupBy("customer_id")
                        .agg(
                            total_spent=_sum("amount"),
                            total_txns=count("*"),
                            avg_txn_value=_sum("amount") / count("*"),
                            first_txn_date=min("txn_date"),
                            last_txn_date=max("txn_date")
                        ))
    
    payment_method_df = (silver_df.groupBy("customer_id", "payment_method")
                        .agg(count("*").alias("payment_count"))
                         .groupBy("customer_id")
                         .agg(max("payment_count").alias("max_payment_count")))
    
    mode_df = (payment_method_df.join(silver_df, on=["customer_id"], how="inner")
               .where(col("payment_count") == col("max_payment_count"))
              .drop("max_payment_count", "payment_count"))
    
    customer_ltv_df = customer_ltv_df.join(mode_df, on="customer_id", how="left")
    customer_ltv_df = customer_ltv_df.withColumn("preferred_payment_method", col("payment_method"))
    customer_ltv_df = customer_ltv_df.drop("payment_method")
    
    customer_ltv_df.write.mode("overwrite").parquet(output_path)

def build_daily_summary(spark, silver_path, output_path, run_date):
    silver_df = (spark.read.format("delta").load(silver_path)
                 .where(col("txn_date") == run_date)
                 .cache())
    
    if silver_df.rdd.isEmpty():
        raise Exception("E003: silver.transactions is missing or empty")
    
    daily_summary_df = (silver_df.groupBy("date")
                        .agg(
                            total_revenue=_sum(when(col("status") == "COMPLETED", col("amount")).otherwise(0)),
                            total_txns=count("*"),
                            unique_customers=countDistinct("customer_id"),
                            unique_merchants=countDistinct("merchant_id"),
                            failed_txns=count(when(col("status") == "FAILED", 1))
                        )
                        .withColumn("failure_rate_pct", (col("failed_txns") / col("total_txns")) * 100)
                       .drop("failed_txns"))
    
    daily_summary_df.write.partitionBy("date").mode("overwrite").parquet(output_path)
