"""
Sigma DataTech Transaction Analytics Pipeline
AI-Generated by Module 1 | Day 7 — Pipeline Brain
Generated: 2026-05-26T09:18:22.334015+00:00

This file was produced by 1_spec_to_pipeline.py from a plain-English spec.
It is a FIRST DRAFT — review before running against production data.

Architecture: Bronze -> Silver -> Gold (medallion pattern)
"""

# ═══════════════════════════════════════════════════════════════
# SECTION 1: BRONZE + SILVER LAYERS
# ═══════════════════════════════════════════════════════════════
from pyspark.sql import SparkSession
from pyspark.sql.functions import col, current_date, lit, coalesce, when, broadcast
from pyspark.sql.types import StructType, StructField, StringType, DoubleType, DateType
from datetime import datetime
import sys

def ingest_bronze(spark, input_path, output_path, run_date, run_id):
    # Read CSV with all columns as strings
    schema = StructType([
        StructField("transaction_id", StringType(), True),
        StructField("customer_id", StringType(), True),
        StructField("amount", StringType(), True),
        StructField("txn_date", StringType(), True),
        StructField("status", StringType(), True)
    ])
    bronze_df = spark.read.csv(input_path, schema=schema, header=True)
    
    # Add ingestion metadata
    bronze_df = bronze_df.withColumn("_ingestion_ts", current_date()) \
                         .withColumn("_source_file", lit(input_path)) \
                        .withColumn("_batch_id", lit(run_id))
    
    # Write Parquet partitioned by txn_date
    bronze_df.write.mode('overwrite').partitionBy("txn_date").parquet(output_path)

def transform_silver(spark, bronze_path, merchants_path, output_path, run_date):
    # Read Bronze Parquet with partition pruning on run_date
    bronze_df = spark.read.parquet(bronze_path).where(col("txn_date") == run_date).cache()
    
    # Check if DataFrame is empty
    if bronze_df.rdd.isEmpty():
        print("Error: E001 - silver.transactions is missing or empty", file=sys.stderr)
        return
    
    # Cast columns to correct types
    silver_df = bronze_df.withColumn("amount", col("amount").cast(DoubleType())) \
                         .withColumn("txn_date", col("txn_date").cast(DateType())) \
                         .withColumn("transaction_id", col("transaction_id").cast(StringType())) \
                         .withColumn("status", col("status").cast(StringType())) \
                        .withColumn("customer_id", col("customer_id").cast(StringType()))
    
    # Filter NULL transaction_id and negative amounts
    silver_df = silver_df.filter(col("transaction_id").isNotNull() & (col("amount") >= 0))
    
    # Deduplicate on transaction_id keeping latest _ingestion_ts
    silver_df = silver_df.withColumn("rank", 
                                     when(col("_ingestion_ts").isNotNull(), col("_ingestion_ts"))
                                    .otherwise(col("_ingestion_ts").cast(DoubleType()).cast("timestamp"))
                                     ).orderBy("transaction_id", col("rank").desc()).distinct(["transaction_id"])
    
    # Read merchants data and broadcast hint
    merchants_df = spark.read.parquet(merchants_path).hint("broadcast")
    merchants_df.cache()
    
    # Join with merchants
    silver_df = silver_df.join(merchants_df, on="customer_id", how="left")
    
    # Add quality_flag column
    silver_df = silver_df.withColumn("quality_flag", 
                                     when(col("customer_id").isNotNull(), "CLEAN").otherwise("UNMATCHED"))
    
    # Write Parquet partitioned by txn_date
    silver_df.write.mode('overwrite').partitionBy("txn_date").parquet(output_path)

def main():
    # Initialize SparkSession
    spark = SparkSession.builder.appName("DataQualityPipeline").getOrCreate()
    
    # Define paths and run date
    input_path = "s3://datalake/bronze/transactions/"
    bronze_path = "s3://datalake/bronze/transactions/"
    merchants_path = "s3://datalake/reference/merchants/"
    silver_path = "s3://datalake/silver/transactions/"
    gold_path = "s3://datalake/gold/data_quality_scorecard/"
    run_date = datetime.now().strftime("%Y-%m-%d")
    run_id = datetime.now().strftime("%Y%m%d%H%M%S")
    
    # Ingest Bronze layer
    ingest_bronze(spark, input_path, bronze_path, run_date, run_id)
    
    # Transform Silver layer
    transform_silver(spark, bronze_path, merchants_path, silver_path, run_date)

if __name__ == "__main__":
    main()


# ═══════════════════════════════════════════════════════════════
# SECTION 2: GOLD AGGREGATION LAYER
# ═══════════════════════════════════════════════════════════════
from pyspark.sql import SparkSession
from pyspark.sql.functions import col, count, countDistinct, sum as sum_, when, lit, coalesce, max as max_, first, isnan, isnull, collect_set, mode
from pyspark.sql.types import StructType, StructField, StringType, DoubleType, IntegerType, DateType, TimestampType

def run_gold(spark, silver_path, gold_output_dir, run_date):
    build_merchant_performance(spark, silver_path, f"{gold_output_dir}/merchant_performance", run_date)
    build_customer_ltv(spark, silver_path, f"{gold_output_dir}/customer_ltv")
    build_daily_summary(spark, silver_path, f"{gold_output_dir}/daily_summary", run_date)
    
    run_metadata = {
        "run_date": run_date,
        "status": "SUCCESS",
        "error_message": None
    }
    
    spark.sparkContext.parallelize([run_metadata]).toDF().write.mode('overwrite').json(f"{gold_output_dir}/run_metadata")

def build_merchant_performance(spark, silver_path, output_path, run_date):
    silver_df = spark.read.format("delta").load(silver_path).filter(col("txn_date") == run_date)
    
    if silver_df.rdd.isEmpty():
        raise Exception("E001: Silver transactions table is empty or missing.")
    
    merchant_performance_df = silver_df.groupBy("merchant_id", "merchant_name", "category", "city", "txn_date") \
        .agg(
            sum_(when(col("status") == "COMPLETED", col("amount")).otherwise(0)).alias("total_revenue"),
            count("*").alias("txn_count"),
            (count(when(col("status") == "FAILED", 1)) / count("*")) * 100.0).alias("failure_rate_pct")
        )
    
    merchant_performance_df.write.partitionBy("txn_date").mode("overwrite").parquet(output_path)

def build_customer_ltv(spark, silver_path, output_path):
    silver_df = spark.read.format("delta").load(silver_path)
    
    customer_ltv_df = silver_df.filter(col("status") == "COMPLETED") \
        .groupBy("customer_id") \
        .agg(
            sum("amount").alias("total_spent"),
            count("*").alias("total_txns"),
            avg("amount").alias("avg_txn_value"),
            first("txn_date").alias("first_txn_date"),
            max("txn_date").alias("last_txn_date"),
            mode("payment_method").alias("preferred_payment_method")
        )
    
    customer_ltv_df.write.mode("overwrite").parquet(output_path)

def build_daily_summary(spark, silver_path, output_path, run_date):
    silver_df = spark.read.format("delta").load(silver_path).filter(col("txn_date") == run_date)
    
    daily_summary_df = silver_df.groupBy("txn_date") \
        .agg(
            sum("amount").alias("total_revenue"),
            count("*").alias("total_txns"),
            countDistinct("customer_id").alias("unique_customers"),
            countDistinct("merchant_id").alias("unique_merchants"),
            (count(when(col("status") == "FAILED", 1)) / count("*")) * 100.0).alias("failure_rate_pct")
        )
    
    daily_summary_df.write.partitionBy("txn_date").mode("overwrite").parquet(output_path)

def ingest_bronze(spark, bronze_path, s3_bronze_path):
    bronze_df = spark.read.format("delta").load(bronze_path)
    bronze_df.write.mode("overwrite").parquet(s3_bronze_path)

def transform_silver(spark, bronze_path, silver_path):
    bronze_df = spark.read.format("delta").load(bronze_path)
    
    silver_df = bronze_df.select(
        bronze_df.transaction_id.cast("string"),
        bronze_df.customer_id.cast("string"),
        bronze_df.amount.cast("double"),
        bronze_df.txn_date.cast("date"),
        bronze_df.status.cast("string"),
        bronze_df._ingestion_ts,
        bronze_df._source_file,
        bronze_df._batch_id
    ).filter(~((bronze_df.txn_date.isNull()) | (bronze_df.txn_date > lit(spark.sparkContext._jsc.sc().currentTime()))))
    
    silver_df = silver_df.drop_duplicates(["transaction_id"], ["_ingestion_ts"]).orderBy("_ingestion_ts", ascending=False)
    silver_df.write.format("delta").mode("overwrite").partitionBy("txn_date").save(silver_path)

def build_gold(spark, silver_path, gold_output_dir, run_date):
    silver_df = spark.read.format("delta").load(silver_path).where(col("txn_date") == run_date)
    
    if silver_df.rdd.isEmpty():
        raise Exception("E001: Silver transactions table is empty or missing.")
    
    # Compute null rates per column
    null_rates = {col: (silver_df.filter(isnull(col(col))).count() / silver_df.count()) * 100 for col in silver_df.columns}
    
    # Compute duplicate rate
    duplicate_rate = (silver_df.count() - silver_df.dropDuplicates(["transaction_id"]).count()) / silver_df.count()
    
    # Check schema match
    required_columns = {'transaction_id', 'customer_id', 'amount', 'txn_date','status'}
    schema_match = 1 if required_columns.issubset(set(silver_df.columns)) else 0
    
    # Compute overall quality score
    overall_quality_score = 100 - (null_rates.get('amount', 0) * 40 + duplicate_rate * 40 + (1 - schema_match) * 20)
    
    # Determine pipeline status
    pipeline_status = "HALTED" if overall_quality_score < 60 else "SUCCESS"
    schema_alert = True if schema_match == 0 and overall_quality_score >= 60 else False
    
    # Create data quality scorecard row
    data_quality_scorecard = [
        (run_date, "ALL", null_rates.get('amount', 0), duplicate_rate, schema_match, overall_quality_score, pipeline_status, schema_alert)
    ]
    
    for col, null_rate in null_rates.items():
        if col not in required_columns:
            data_quality_scorecard.append((run_date, col, null_rate, duplicate_rate, schema_match, overall_quality_score, pipeline_status, schema_alert))
    
    # Write to gold.data_quality_scorecard
    schema = StructType([
        StructField("run_date", DateType(), True),
        StructField("column_name", StringType(), True),
        StructField("null_rate", DoubleType(), True),
        StructField("duplicate_rate", DoubleType(), True),
        StructField("schema_match", IntegerType(), True),
        StructField("overall_quality_score", DoubleType(), True),
        StructField("pipeline_status", StringType(), True),
        StructField("schema_alert", BooleanType(), True)
    ])
    
    data_quality_df = spark.createDataFrame(data_quality_scorecard, schema)
    data_quality_df.write.mode("overwrite").parquet(f"{gold_output_dir}/data_quality_scorecard")
    
    if pipeline_status == "HALTED":
        raise Exception("Pipeline halted due to low data quality score.")
    elif schema_alert:
        # Send warning to governance team
        pass
