-- models/marts/mart_merchant_kpis.sql

WITH filtered_transactions AS (
    SELECT
        transaction_id,
        amount,
        status,
        merchant_id,
        customer_id,
        transaction_date,
        payment_method
    FROM {{ ref('stg_fact_transactions') }}
    WHERE status IN ('COMPLETED', 'FAILED')
),

merchant_details AS (
    SELECT
        merchant_id,
        merchant_name,
        category,
        city,
        onboarded_date
    FROM {{ ref('stg_dim_merchant') }}
),

aggregated_metrics AS (
    SELECT
        ft.merchant_id,
        COUNT(ft.transaction_id) AS total_transactions,
        COUNT(DISTINCT ft.customer_id) AS unique_customers,
        SUM(CASE WHEN ft.status = 'COMPLETED' THEN ft.amount ELSE 0 END) AS total_revenue,
        COUNT(CASE WHEN ft.status = 'FAILED' THEN 1 END) AS failed_count,
        AVG(CASE WHEN ft.status = 'COMPLETED' THEN ft.amount ELSE NULL END) AS avg_transaction_value
    FROM filtered_transactions ft
    GROUP BY ft.merchant_id
),

final_kpis AS (
    SELECT
        md.merchant_id,
        md.merchant_name,
        md.category,
        md.city,
        md.onboarded_date,
        am.total_transactions,
        am.unique_customers,
        am.total_revenue,
        am.failed_count,
        (am.failed_count::FLOAT / am.total_transactions) * 100 AS failure_rate_pct,
        am.avg_transaction_value
    FROM aggregated_metrics am
    JOIN merchant_details md ON am.merchant_id = md.merchant_id
)

SELECT * FROM final_kpis
```

```yaml
# models/marts/schema.yml

version: 2

models:
  - name: mart_merchant_kpis
    description: "Aggregated merchant KPIs including total revenue, total transactions, failed count, failure rate, average transaction value, and unique customers."
    columns:
      - name: merchant_id
        description: "Unique identifier for the merchant."
      - name: merchant_name
        description: "Name of the merchant."
      - name: category
        description: "Category of the merchant."
      - name: city
        description: "City where the merchant is located."
      - name: onboarded_date
        description: "Date when the merchant was onboarded."
      - name: total_transactions
        description: "Total number of transactions for the merchant."
      - name: unique_customers
        description: "Number of unique customers who made transactions with the merchant."
      - name: total_revenue
        description: "Total revenue generated by the merchant from completed transactions."
      - name: failed_count
        description: "Number of failed transactions for the merchant."
      - name: failure_rate_pct
        description: "Failure rate percentage of transactions for the merchant."
      - name: avg_transaction_value
        description: "Average value of completed transactions for the merchant."

tests:
  - generic_test:
      model: mart_merchant_kpis
      column_name: merchant_id
      test: not_null

  - generic_test:
      model: mart_merchant_kpis
      column_name: merchant_name
      test: not_null

  - generic_test:
      model: mart_merchant_kpis
      column_name: total_transactions
      test: not_null

  - generic_test:
      model: mart_merchant_kpis
      column_name: unique_customers
      test: not_null

  - generic_test:
      model: mart_merchant_kpis
      column_name: total_revenue
      test: not_null

  - generic_test:
      model: mart_merchant_kpis
      column_name: failed_count
      test: not_null

  - generic_test:
      model: mart_merchant_kpis
      column_name: failure_rate_pct
      test: not_null

  - generic_test:
      model: mart_merchant_kpis
      column_name: avg_transaction_value
      test: not_null
