"""
Lambda Tool: write_incident_report
Called by: Incident Report Agent
Action group: DataPlatformTools

Compiles all agent findings into a structured post-mortem.
Writes markdown to S3 reports/ so the CTO can read it.
Also saves a JSON version for downstream tools/dashboards.
"""

import boto3, json, os
from datetime import datetime, timezone


def lambda_handler(event, context):
    params = {p["name"]: p["value"] for p in event.get("parameters", [])}

    findings = json.loads(params.get("findings", "{}"))
    bucket   = params.get("bucket", os.getenv("SIGMA_S3_BUCKET", ""))
    region   = os.getenv("AWS_DEFAULT_REGION", "us-east-1")

    result = write_report(findings, bucket, region)

    return {
        "messageVersion": "1.0",
        "response": {
            "actionGroup": event.get("actionGroup"),
            "function": event.get("function"),
            "functionResponse": {
                "responseBody": {"TEXT": {"body": json.dumps(result, default=str)}}
            },
        },
    }


def write_report(findings: dict, bucket: str, region: str) -> dict:
    if not bucket:
        return {"error": "SIGMA_S3_BUCKET not set"}

    s3  = boto3.client("s3", region_name=region)
    ts  = datetime.now(timezone.utc)
    key = f"reports/incident_{ts.strftime('%Y%m%d_%H%M%S')}.md"

    forensics  = findings.get("forensics",  {})
    impact     = findings.get("impact",     {})
    recovery   = findings.get("recovery",   {})
    rollback   = findings.get("rollback",   {})
    hardening  = findings.get("hardening",  {})

    # Build the markdown report
    md = f"""# Incident Report — {impact.get('gmv_gap_inr', 'Unknown')} GMV Loss — {ts.strftime('%Y-%m-%d')}

**Severity:** {findings.get('severity', 'HIGH')}
**Detection time:** {findings.get('detection_ts', ts.isoformat())}
**Recovery time:** {ts.isoformat()}
**Total downtime:** {findings.get('downtime_minutes', '?')} minutes
**Human interventions:** 0

---

## Summary

{findings.get('summary', 'Silent pipeline failure. Records unloaded. Root cause identified and fixed by autonomous agent system.')}

---

## Timeline

| Time (UTC) | Event |
|---|---|
{_build_timeline(findings)}

---

## Root Cause

{forensics.get('root_cause_hypothesis', 'See forensics findings.')}

**Anomaly window:** {forensics.get('anomaly_window', {}).get('detected_at', '?')}
**Trigger:** {forensics.get('anomaly_window', {}).get('trigger', '?')}
**Correlation:** {forensics.get('anomaly_window', {}).get('correlation', '?')}

### Why no alert fired
The existing CloudWatch alarm threshold was set to a value that the missing
GMV did not exceed during the failure window. The `sigma-pipeline-row-divergence`
alarm created by the Hardening Agent would have fired within 10 minutes.
It is now active.

---

## Business Impact

| Metric | Value |
|---|---|
| Transactions unloaded | {impact.get('records_missing', '?')} |
| GMV gap | {impact.get('gmv_gap_inr', '?')} |
| Time window | {impact.get('failure_window', '?')} |
| Merchants affected | {impact.get('merchants_affected', '?')} |
| SLA breach | {impact.get('sla_breach', 'None confirmed')} |
| Notification required | {impact.get('notification_required', 'Check SLA contracts')} |

---

## Fix Applied

{_build_fix_section(recovery, rollback)}

---

## Prevention — Alarms Created

The following CloudWatch alarms were created by the Hardening Agent
and are **live in the AWS account** as of {ts.strftime('%H:%M UTC')}:

{_build_alarms_section(hardening)}

### Recommended (not yet implemented)
Lambda deployment policy requiring canary traffic (10% for 5 minutes)
before full rollout. See `deploy/lambda_canary_policy.json` for proposal.

---

## Agent Performance

| Agent | Time (sec) | Tool calls | Key finding |
|---|---|---|---|
{_build_agent_perf(findings)}

**Total recovery time: {findings.get('total_duration_sec', '?')} seconds**

---

*Generated by Sigma Intelligence Platform — Incident Report Agent*
*{ts.isoformat()}*
"""

    # Write markdown to S3
    s3.put_object(
        Bucket=bucket, Key=key,
        Body=md.encode("utf-8"),
        ContentType="text/markdown",
    )

    # Write JSON version for dashboards
    json_key = key.replace(".md", ".json")
    s3.put_object(
        Bucket=bucket, Key=json_key,
        Body=json.dumps(findings, indent=2, default=str).encode("utf-8"),
        ContentType="application/json",
    )

    return {
        "status":     "WRITTEN",
        "report_md":  f"s3://{bucket}/{key}",
        "report_json": f"s3://{bucket}/{json_key}",
        "written_at": ts.isoformat(),
    }


def _build_timeline(findings: dict) -> str:
    events = findings.get("timeline", [])
    if not events:
        return "| ? | Failure window — see forensics findings |"
    return "\n".join(
        f"| {e.get('ts','?')} | {e.get('event','?')} |" for e in events
    )


def _build_fix_section(recovery: dict, rollback: dict) -> str:
    lines = []
    if rollback.get("status") == "SUCCESS":
        b = rollback.get("before", {})
        a = rollback.get("after", {})
        lines.append(f"- **Lambda rolled back:** {rollback.get('function_name','?')} "
                     f"alias {rollback.get('alias','LIVE')} "
                     f"v{b.get('version','?')} → v{a.get('version','?')}")
    if recovery.get("rows_loaded"):
        lines.append(f"- **Records replayed:** {recovery.get('rows_loaded','?')} "
                     f"loaded, {recovery.get('rows_skipped','0')} duplicates skipped")
    if recovery.get("quarantined_count"):
        lines.append(f"- **Records quarantined:** {recovery.get('quarantined_count','?')} "
                     f"({recovery.get('quarantine_reason','?')})")
    return "\n".join(lines) if lines else "See recovery agent findings."


def _build_alarms_section(hardening: dict) -> str:
    alarms = hardening.get("alarms_created", [])
    if not alarms:
        return "- See hardening agent findings."
    return "\n".join(
        f"- **{a.get('alarm_name','?')}** — {a.get('description','?')}"
        for a in alarms
    )


def _build_agent_perf(findings: dict) -> str:
    perf = findings.get("agent_performance", [])
    if not perf:
        return "| — | — | — | — |"
    return "\n".join(
        f"| {p.get('agent','?')} | {p.get('duration_sec','?')} | "
        f"{p.get('tool_calls','?')} | {p.get('key_finding','?')} |"
        for p in perf
    )


# ── Local test ────────────────────────────────────────────────────────────────
if __name__ == "__main__":
    import sys
    from dotenv import load_dotenv
    load_dotenv()

    sample_findings = {
        "severity": "HIGH",
        "summary": "Lambda v2 deployed at 02:11 UTC changed field names. "
                   "Snowflake loaded 0 rows. 847 transactions missing.",
        "downtime_minutes": 420,
        "total_duration_sec": 26,
        "timeline": [
            {"ts": "02:11 UTC", "event": "Lambda v2 auto-deployed"},
            {"ts": "02:12 UTC", "event": "Firehose delivers malformed JSON to S3"},
            {"ts": "02:12 UTC", "event": "Snowflake COPY INTO loads 0 rows silently"},
            {"ts": "09:03 UTC", "event": "Business analyst notices ₹0 GMV"},
            {"ts": "09:03 UTC", "event": "Supervisor agent triggered"},
            {"ts": "09:03:26 UTC", "event": "Pipeline restored. 3 alarms created."},
        ],
        "forensics": {
            "root_cause_hypothesis": "Lambda v2 renamed merchant_name→merchant_nm and changed date format.",
            "anomaly_window": {
                "detected_at": "2026-06-04T02:11:00Z",
                "trigger": "Lambda version 2 deployed",
                "correlation": "v2 deploy → malformed JSON → 0 Snowflake rows",
            },
        },
        "impact": {
            "records_missing": 847, "gmv_gap_inr": "₹4,72,340",
            "failure_window": "02:11–02:15 UTC",
            "merchants_affected": 12,
            "sla_breach": "QuickMart — ₹1,21,450 (threshold ₹50,000)",
            "notification_required": "Yes — QuickMart within 2 hours",
        },
        "recovery": {
            "rows_loaded": 824, "rows_skipped": 0,
            "quarantined_count": 23, "quarantine_reason": "null_transaction_id",
        },
        "rollback": {
            "status": "SUCCESS", "function_name": "sigma-kinesis-producer",
            "alias": "LIVE", "before": {"version": "2"}, "after": {"version": "1"},
        },
        "hardening": {
            "alarms_created": [
                {"alarm_name": "sigma-snowflake-zero-load",
                 "description": "Fires if COPY INTO loads 0 rows consecutively"},
                {"alarm_name": "sigma-lambda-version-change",
                 "description": "Fires on Lambda error spike after version change"},
                {"alarm_name": "sigma-pipeline-row-divergence",
                 "description": "Fires if Kinesis/Snowflake row count diverges > 5%"},
            ]
        },
        "agent_performance": [
            {"agent": "Forensics", "duration_sec": 4, "tool_calls": 3, "key_finding": "Lambda v2 at 02:11"},
            {"agent": "Impact",    "duration_sec": 2, "tool_calls": 2, "key_finding": "₹4.72L, SLA breach"},
            {"agent": "Recovery",  "duration_sec": 9, "tool_calls": 4, "key_finding": "824 replayed"},
            {"agent": "Rollback",  "duration_sec": 5, "tool_calls": 2, "key_finding": "v1 restored"},
            {"agent": "Hardening", "duration_sec": 4, "tool_calls": 3, "key_finding": "3 alarms created"},
            {"agent": "Incident",  "duration_sec": 2, "tool_calls": 1, "key_finding": "Report written"},
        ],
    }

    bucket = os.getenv("SIGMA_S3_BUCKET", "")
    region = os.getenv("AWS_DEFAULT_REGION", "us-east-1")

    if not bucket:
        print("Set SIGMA_S3_BUCKET in .env to test")
    else:
        result = write_report(sample_findings, bucket, region)
        print(json.dumps(result, indent=2))
        print(f"\nDownload: aws s3 cp {result['report_md']} ./incident_report.md")

    if "--test" in sys.argv:
        print("\nwrite_incident_report.py test PASSED")
